- name: Create S3 bucket
  hosts: localnode
  gather_facts: false
  roles:
    - storage

- name: Prepare server and deploy the application
  hosts: webservers
  become: true
  roles:
    - common
    - node_exporter
    - deploy
    - nginx
